echo "[Desktop Entry]">"osa.desktop"
echo "Version=1.0">>"osa.desktop"
echo "Name=OSA">>"osa.desktop"
echo "Comment=OSA">>"osa.desktop"
echo "Type=Application">>"osa.desktop"
echo "Exec="$PWD"/OSA">>"osa.desktop"
echo "Icon="$PWD"/resources/icon/iconb.png">>"osa.desktop"
echo "Terminal=false">>"osa.desktop"
chmod u+x "osa.desktop"
